Dashboard/urls.py
from django.urls import path
from Dashboard import views

app_name='Dashboard'

urlpatterns = [
    path('', views.home, name="home"),
    path('cadastra_produto/', views.cadastra_produto, name='cadastra_produto'),
    path('exibe_produto/<int:id>/', views.exibe_produto, name='exibe_produto'),
    path('edita_produto/<int:id>/', views.edita_produto, name='edita_produto'),
    path('remove_produto/', views.remove_produto, name='remove_produto'),
    #path('pesquisa_produto/', views.pesquisa_produto, name='pesquisa_produto'),
    path('lista_produto/', views.lista_produto, name='lista_produto'),
    #path('<slug:slug_da_categoria>/', views.produto_lista, name="produto_lista_por_categoria"),
    #re_path(r'^(?P<slug>[\w_-]+)/$', views.categoria, name="categoria"),
    #path('<slug:slug_da_categoria>/<int:id>/<slug:slug_do_produto>/', views.produto_exibe, name='produto_exibe'),
]

autenticacao/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from autenticacao.forms import AuthenticationFormCustomizado


app_name = 'autenticacao'
 
urlpatterns = [
   path('login/', auth_views.LoginView.as_view(authentication_form=AuthenticationFormCustomizado), 
                                               name='login'),
   path('register/', views.RegisterView.as_view(),name='register'),                                             
   path('logout/', auth_views.LogoutView.as_view(), name='logout')                                               
]

catalogo/urls.py
from django.urls import path
from . import views

app_name='catalogo'

urlpatterns = [
    path('', views.produto_lista, name="produto_lista"),
    path('<slug:slug_da_categoria>/', views.produto_lista, name="produto_lista_por_categoria"),
    #re_path(r'^(?P<slug>[\w_-]+)/$', views.categoria, name="categoria"),
    path('<slug:slug_da_categoria>/<int:id>/<slug:slug_do_produto>/', views.produto_exibe, name='produto_exibe'),
    
]

core/urls.py
from django.urls import path
from . import views


app_name='core'

urlpatterns = [
    path('contato/', views.contato, name="contato"),
    path('minhaconta/', views.minhaconta, name="minhaconta"),
    path('carrinho/',  views.adiciona_produto_carrinho, name='carrinho'),
    path('carrinho/remove', views.remove_produto_carrinho, name='remove'),
    path('carrinho/modifica', views.modifica_produto_carrinho, name='modifica'),
    

    
]

projeto/urls.py
from django.urls import path
from django.conf.urls import include
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from catalogo.models import Categoria

urlpatterns = [
    #path('',views.index, name='index'),
    path('admin2/', admin.site.urls),
    path('admin/', include('Dashboard.urls',namespace='dashboard')),
    path('', include('core.urls',namespace='contato')),
    path('', include('core.urls',namespace='minhaconta')),
    
    #path('entrar/', LoginView.as_view(extra_context={'categorias': categorias}) ,name='login'),
    #path('sair/', LogoutView.as_view(next_page='/'),name='logout'),
    path('', include('catalogo.urls',namespace='catalogo')),
    path('autenticacao/', include('autenticacao.urls',namespace='autenticacao')),
    
]

core/models.py
from django.db import models

# Create your models here.




    
        

core/forms.py
#
from django import forms
from django.core.mail import send_mail
from django.conf import settings
from django.core.validators import RegexValidator
from catalogo.models import Carrinho, Categoria
from projeto import settings
from datetime import datetime, timedelta
class ContatoForm(forms.Form):


    name = forms.CharField(label='Nome',required=True)
    email = forms.EmailField(label='E-mail',required=True)
    message = forms.CharField(label='Mensagem',widget=forms.Textarea())

    #def __init__(self, *args, **kwargs):
        #super(ContatoForm,self).__init__(*args, **kwargs)
        #self.fields['name'].widget.attrs['class'] = 'form-control'
        #self.fields['email'].widget.attrs['class'] = 'form-control'
        #self.fields['message'].widget.attrs['class'] = 'form-control'


    def send_mail(self):
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        message = self.cleaned_data['message']

        message = 'Nome: {0}\n E-mail: {1}\n{2}'.format(name,email,message)
        send_mail(
            'Contato Loja Virtual Django', message, settings.DEFAULT_FROM_EMAIL, 
            [settings.DEFAULT_FROM_EMAIL]
        )
            
class AtualizaProdutoCarrinhoForm(forms.ModelForm):

    class Meta:
        model = Carrinho
        fields = ('quantidade',)

    quantidade = forms.CharField(
        error_messages={'required': 'Campo obrigatório.', },
        validators=[RegexValidator(regex='^[0-9]{1,5}$', message="Informe o valor no formato 99999.")],
        widget=forms.TextInput(attrs={'class': 'form-control form-control-sm quantidade',
                                      'maxlength': '5',
                                      'onkeypress': 'return event.charCode >= 48 && event.charCode <= 57'}),
        required=True)

class CarrinhoForm(forms.ModelForm):

    class Meta:
        model = Carrinho
        fields = ('produto_id','categoria', 'nome', 'quantidade', 'preco')

    produto_id = forms.CharField(widget=forms.HiddenInput(), required=False)

    # <input type="hidden" name="produto_id" id="id_produto_id" value="xxx">


    categoria = forms.ModelChoiceField(
        error_messages={'required': 'Campo obrigatório.', },
        queryset=Categoria.objects.all().order_by('nome'),
        empty_label='--- Selecione uma categoria ---',
        widget=forms.Select(attrs={'class': 'form-control form-control-sm'}),
        required=True)

    #      {{ form.categoria }}
    #      <select name="categoria" class="form-control form-control-sm" required id="id_categoria">
    #          <option value="" selected>--- Selecione um(a) categoria ---</option>
    #          <option value="1">Categoria 1</option>
    #          <option value="2">Categoria 2</option>
    #          <option value="3">Categoria 3</option>
    #      </select>

    nome = forms.CharField(
        error_messages={'required': 'Campo obrigatório.',
                        'unique': 'Produto duplicado.'},
        widget=forms.TextInput(attrs={'class': 'form-control form-control-sm', 'maxlength': '120'}),
        required=True)

    # <input type="text"
    #        name="nome"
    #        id="id_nome"
    #        class="form-control form-control-sm"
    #        maxlength="120"
    #        required>

    quantidade = forms.CharField(
        error_messages={'required': 'Campo obrigatório.', },
        validators=[RegexValidator(regex='^[0-9]{1,5}$', message="Informe o valor no formato 99999.")],
        widget=forms.TextInput(attrs={'class': 'form-control form-control-sm',
                                      'maxlength': '5',
                                      'onkeypress': 'return event.charCode >= 48 && event.charCode <= 57'}),
        required=True)
    
    # NumberInput NÃO É SUPORTADO POR TODOS OS BROWSERS - EVITAR POR ENQUANTO

    # <input type='text'
    #        name='data_cadastro'
    #        class='form-control form-control-sm'
    #        required=''
    #        id='id_data_cadastro'
    #        maxlength='10'>

    preco = forms.CharField(
        localize=True,
        error_messages={'required': 'Campo obrigatório.', },
        validators=[RegexValidator(regex='^[0-9]{1,7}(,[0-9]{2})?$', message="Informe o valor no formato 9999999,99.")],
        widget=forms.TextInput(attrs={'class': 'form-control form-control-sm',
                                      'maxlength': '10',
                                      'onkeypress': 'return (event.charCode >= 48 && event.charCode <= 57) || event.charCode == 44'}),
        required=True)

    # <input type="text"
    #        name="preco"
    #        id="id_preco"
    #        class="form-control form-control-sm"
    #        maxlength="10"
    #        onkeypress="return (event.charCode >= 48 &amp;&amp; event.charCode <= 57) || event.charCode == 44"
    #        required="">

    def clean_preco(self):
        preco = self.cleaned_data.get('preco')
        
        if not preco:
            return preco
        
        preco = Decimal(preco.replace(',', '.'))

        return preco
        
class RemoveProdutoCarrinhoForm(forms.Form):
    class Meta:
        fields = ('produto_id')

    produto_id = forms.CharField(widget=forms.HiddenInput(), required=True)

    # <input type="hidden" name="produto_id" id="id_produto_id" value="xxx">
       

core/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from catalogo.models import Categoria,Carrinho,Produto
from django.shortcuts import get_object_or_404
from .forms import ContatoForm, CarrinhoForm, AtualizaProdutoCarrinhoForm
from django.core.mail import send_mail
from django.conf import settings
from django.views.generic import View, TemplateView
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from datetime import datetime, timedelta
from django.db.models import Sum, F, FloatField
from django.urls import reverse
import json
from rest_framework import serializers
class IndexView(TemplateView):

    template_name = 'produto_lista.html'


index = IndexView.as_view()

# @login_required
def contato(Request):
    
    success= False
    form = ContatoForm(Request.POST or None)
    if form.is_valid():
        form.send_mail()
        success= True
    context = {
        'form': form,
        'success': success
    }
    return render(Request,'contato.html',context)

@login_required
def minhaconta(Request):
    
    context = {
        "teste": "teste"
    }
    return render(Request,'minhaconta.html',context)

@login_required
def adiciona_produto_carrinho(request):
    if request.POST:
        user = request.user
        print(request.POST['pro_id'])
        if user:
            produto = Produto.objects.get(id=request.POST['pro_id'])
    
            carrinho = Carrinho()
            
            carrinho.user = request.user
            carrinho.produto = produto
            carrinho.quantidade = 1
            carrinho.preco = produto.price
            carrinho.save()

            
            carrinho =  Carrinho.objects.filter(
                user=user,
            ).order_by('id')

            resultado = carrinho.aggregate(
            total=Sum(F('quantidade') * F('preco'), output_field=FloatField()))
   
            if resultado['total']:
                total = '{0:.2f}'.format(resultado['total'])
            else:
                total = '0,00'
            
            lista_de_ids = []
            for car in carrinho:
                lista_de_ids.append(car.id)
            
            

            return render(request, 'carrinho.html', {
                'lista_de_ids':lista_de_ids,
                'produtos': carrinho,
                'total': total
            })

        else:
            raise ValueError('Ocorreu um erro inesperado ao tentar cadastrar um produto.')
    else:
        
        user = request.user
        carrinho = Carrinho.objects.filter(
            user=user,
        ).order_by('id')
        
        resultado = carrinho.aggregate(
        total=Sum(F('quantidade') * F('preco'), output_field=FloatField()))
        
        if resultado['total']:
            total = '{0:.2f}'.format(resultado['total'])
        else:
            total = '0,00'

        #sub-total_list = []
        lista_de_ids = []
        for car in carrinho:
            lista_de_ids.append(car.id)
            #lista_de_forms.append(AtualizaProdutoCarrinhoForm(initial={'quantidade': car.quantidade}))

        return render(request, 'carrinho.html', {
        
        'produtos': carrinho,
        'lista_de_ids':lista_de_ids,
        'total': total
    })

def remove_produto_carrinho(request):
    
    total=0
    if request.POST:
        if request.POST.get("acao") == "limpar":
            carrinho = Carrinho.objects.all()
            for car in carrinho:
                car.delete()
        else:

            carrinho_id = request.POST.get('pro_id')
            carrinho = get_object_or_404(Carrinho, id=carrinho_id)
            carrinho.delete()

    carrinho = Carrinho.objects.filter(
            user=request.user,
        ).order_by('id')        
    
    resultado = carrinho.aggregate(
    total=Sum(F('quantidade') * F('preco'), output_field=FloatField()))
        
   
    if resultado['total']:
        total = '{0:.2f}'.format(resultado['total'])
    else:
        total = '0,00'
    print(total)
   
    
    return JsonResponse({'total':total})
    

@login_required
class CarrinhoView(View):

    def post(self, request):
        return render(request,'carrinho.html',context)



    def get(self, request):
        print(request.user)
        context = {
        "teste": "teste"
        }
        return render(request,'carrinho.html',context)

def modifica_produto_carrinho(request):
    total=0
    if request.GET:
        
        
        carrinho_id = request.GET.get('pro_id')
        quantidade = request.GET.get('quantidade ')
        carrinho = get_object_or_404(Carrinho, id=carrinho_id)
        carrinho.quantidade = quantidade
        sub_total = int(quantidade) * carrinho.preco
        carrinho.save()
           

   
    
    resultado = Carrinho.objects.all().aggregate(
    total=Sum(F('quantidade') * F('preco'), output_field=FloatField())
    )
        
   
    if resultado['total']:
        total = '{0:.2f}'.format(resultado['total'])
    else:
        total = '0,00'
    print(total)
   
    
    return JsonResponse({'total':total,'sub_total':sub_total, 'id':carrinho_id },)

core/templates/base.html
{% load static %}
<html lang="pt-br">

   <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <link href="{% static 'assets/css/bootstrap.css' %} " rel="stylesheet">
      <link href=" {% static 'assets/css/all.css' %}" rel="stylesheet">
      <link href="{% static 'assets/css/styles.css' %} " rel="stylesheet">
      <link href="{% static 'assets/css/addNumber.css' %} " rel="stylesheet">
      <link href="{% static 'assets/css/tema.css' %} " rel="stylesheet" type="text/css"/>
      <link href="{% static 'assets/contatos/contatos.css' %}" rel="stylesheet">
      <title>{% block title %}
            E-Commerce
      {% endblock title %}</title>
      <link rel = "icon" href =  
"https://media.geeksforgeeks.org/wp-content/cdn-uploads/gfg_200X200.png" 
        type = "image/x-icon"> 
   </head>

   <body>
      <!--INICIO CONTAINER GERAL-->
      <div class="container-fluid">
         <!-- INICIO DIV TOPO-->
         <div class="row" id="topo">
            <div class="container">
               <div class="row">
                  <div class="col-md-6">
                     <img src="{% static 'assets/imagens/logo.png' %} " alt=""> 
                              
                  </div>
                  
                  <div class="col-md-6 text-right pt-5">
                     {% if user.is_authenticated %}
                        <div class="dropdown">
                           <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                              Olá:{{ user }}
                           </a>

                           <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                              <a class="dropdown-item" href="{% url 'core:minhaconta' %}">Minha Conta</a>
                              <a class="dropdown-item" href="#">Favoritos</a>
                              <div class="dropdown-divider"></div>
                              {% if user.is_superuser %}
                                 <a class="dropdown-item" href="{% url 'Dashboard:home' %}">Área Restrita</a>
                              {% endif %}  
                              <a class="dropdown-item" href="{% url 'autenticacao:logout' %}">Sair </a>
                           </div>
                        </div>
                     {% else %}
                        <a class="btn btn-secondary" href="{% url 'autenticacao:login' %}" ><i class="fas fa-user"></i> LOGIN|CADASTRE-SE</a>
                     {% endif %}
                     
                  </div> 
               </div>
            </div>
         </div>  

         <div class="row bg-dark" id="barra-menu">
            <div class="container-fluid">
               <nav class="navbar navbar-inverse navbar-expand-lg navbar-dark bg-dark"> 

                  <div class="container">
                     
                     <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#conteudoNavbarSuportado" aria-controls="conteudoNavbarSuportado" aria-expanded="false" aria-label="Alterna navegação">
                        <span class="navbar-toggler-icon"></span>
                     </button>
                     
                     <div class="collapse navbar-collapse" id="conteudoNavbarSuportado">
                        <ul class="navbar-nav mr-auto" >
                           <li class="nav-item ">
                              <a class="nav-link"  href="{% url 'catalogo:produto_lista' %}"><i class="fab fas fa-home"></i> Home</a>
                           </li>
                           <li class="nav-item">
                              <a class="nav-link " href="{% url 'core:minhaconta' %}"><i class="fab fas fas fa-user-circle"></i> Minha Conta</a>
                              
                              
                              
                           </li>
                           <li class="nav-item">
                              <a class="nav-link " href="{% url 'core:carrinho' %}"><i class=" fas fas fa-shopping-cart"></i> Carrinho</a>
                           </li>
                           <li class="nav-item">
                              <a class="nav-link " href="{% url 'core:contato' %}"><i class=" fas fas fas fas fa-file-contract"></i> Contato</a>
                           </li>
                        </ul>
                        <form class="form-inline my-2 my-lg-0">
                           <input class="form-control mr-sm-2" type="search" placeholder="Pesquisar" aria-label="Pesquisar">
                           <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class=" fas fas fa-search"></i> Pesquisar</button>
                        </form>
                     </div>
                  </div> <!-- fim navbar collapse--> 
               </nav><!-- fim da navBar-->
            </div><!-- fim do container--> 
         </div> <!-- fim barra menu--> 

         <!-- Comeca DIV CONTEUDO-->
         <br>
         <div class="row" id="conteudo"> 
            <div class="container">
               <div class="row">

                  <!-- coluna da esquerda -->
                  <div class="col-md-2 " id="lateral">
                     <div class="list-group">
                        <span class="list-group-item active" style="background-color:#204d74">Categorias</span>
                       <a href="{% url 'catalogo:produto_lista' %}"><span class="list-group-item {% if not categoria %}active{% endif %}"><i class="fas fa-angle-right"></i> Todos</span></a>
                        {% for cat  in categorias %}
                           <a href="{{ cat.get_absolute_path }}" class="list-group-item {% if cat == categoria%}active{% endif %}"><i class="fas fa-angle-right"></i> {{cat.name}}</a> 
                        {% endfor %}

                        
                                          
                        
                     </div><!--fim da list group-->              
                  </div> <!-- finm coluna esquerda -->
                  <div class="col-md-10" id="lateral-conteudo">
                     
                     <!-- =============== AQUI VAI TODO O CONTEUDO DO SITE OU DINAMICO  -->
                     <!-- ============== INICIO DO CAROUSE ==================-->
                     {% block conteudo %}
                     {% endblock conteudo %}

                     
                  </div><!-- Fim Container Conteudo-->  
               </div>
            </div>
         </div> <!-- Fim Container Geral-->  
     
     <br>
     
     
     <div class="row" id="rodape"><!-- começa div rodape -->
                 
             <div class="container">
                  <h4>TITULO_SITE</h4>
                  <P>Todos os Direitos Reservados - Jorge Stief - Pirueba - {{ data }}</P>
              </div>
         
     
     </div><!-- fim div rodape-->
      

      <script src="{% static 'assets/js/jquery-3.3.1.js' %} "></script>
      <script src="{% static 'assets/js/popper.js' %}"></script>
      <script src="{% static 'assets/js/bootstrap.js' %}"></script>
      <script src="{% static 'assets/js/script.js' %}"></script>
      <script src="{% static 'assets/js/addNumber.js' %}"></script>
      <script src="{% static 'assets/contatos/contatos.js' %}"></script>
      <script>
            $(document).ready(function(){    
            
               // validar frete
                 $('#buscar_frete').click(function(){  
                    
                  var CEP_CLIENTE = $('#cep_frete').val();
                  var PESO_FRETE = $('#peso_frete').val();
                   
                    if (CEP_CLIENTE.length !== 8 ) {
                    alert('Digite seu CEP corretamente, 8 dígitos e sem traço ou ponto');  
                     $('#frete').addClass(' text-center text-danger');
                     $('#frete').html('<b>Digite seu CEP corretamente, 8 dígitos e sem traço ou ponto</b>');
                    $('#cep_frete').focus();
                    } else {
                 
                   
                    $('#frete').html('<img src="view/images/loader.gif"> <b>Carregando...</b>');
                    $('#frete').addClass(' text-center text-danger');
                  
                    // carrego o combo com os bairros
                   
                    $('#frete').load('controller/frete.php?cepcliente='+CEP_CLIENTE+'&pesofrete='+PESO_FRETE);
             
             } // fim do IF digitei o CEP
                  
             
                }); // fim do change
                
               
            } ); // fim do ready
            
    </script>
    <script>
        $(document).ready(function(){
            {% block domready %}

            {% endblock %}
        });
    </script>
   </body>

</html>

core/templates/carrinho.html
{% extends 'base.html' %}

{% load static %}
{% load widget_tweaks %}
{% load mathfilters %}
{% block title %}
Carrinho | {{block.super}}
{% endblock title %}

{% block conteudo %}
<div id="ajax">
<h3 class="text-center">Meu Carrinho</h3>
                           
                    <!-- botoes e opções de cima -->
                    <div class="row float-right">
                        <div class="col-md-12  ">
                            <a href="{% url 'catalogo:produto_lista' %}" class="btn btn-info" title="">Comprar Mais</a>
                        </div>
                       
                    </div>
                    <br>
                    <br>
                    <!--  table listagem de itens -->
                    <div class="row ">
                        <table class="table table-bordered ml-4" style="width: 95%">
                           <tr class="text-white " style="background-color: #204d74">
                                <td></td> 
                                <td>Produto</td> 
                                <td>Valor R$</td> 
                                <td>X</td> 
                                <td>Sub Total R$</td> 
                                <td></td> 
                                        
                            </tr>
                            {% for carrinho in produtos %}
                            <tr>
                                 <td style="display:none">{{carrinho.id}}</td>       
                                <td> <img src="assets/imagens/calca02.jpg" width="80px" height="80px" alt="calça"> </td>
                                <td> {{carrinho.produto}}</td>
                                <td >  {{carrinho.preco}}</td>
                                
                                    <td > 
                                        <input class="addNumber" name="quantidade" id="{{carrinho.id}}" type="text" value="{{carrinho.quantidade}}"/>
                                        
                                    </td>
                                <td class="sub_total">  {{ carrinho.quantidade|mul:carrinho.preco}}</td>
                                <td> 
                                    <form name="" method="post" action="{% url 'core:remove'%}" novalidate>
                                        {% csrf_token %}
                                        <input type="hidden" name="acao" value="excluir"> 
                                        <button type="button" class="btn btn-danger btn-sm remover"> Excluir </button>
                                    </form>
                                </td>
                                        
                                        
                            </tr>
                            {% endfor %}
                        </table>           
                    </div><!-- fim da listagem itens -->
                    <!--  bloco frete -->
                    <div class="row" id="dadosfrete">
                        <div class="col-md-4"></div>
                        <div class="col-md-4">
                        <!-- campos para tratar  do  frete -->
                            <input type="hidden" name="peso_frete" id="peso_frete" value="{$PESO}" class="form-control " readonly>
                            <input type="text" name="cep_frete" class="form-control" id="cep_frete" value="" placeholder="digite seu cep" >
                            <input type="hidden" name="frete_valor" id="frete_valor" value="0">
                        </div> 
                        <div class="col-md-4">
                            <!-- botão frete -->
                            <button class="btn btn-outline-warning btn-block" id="buscar_frete"> <i class="glyphicon glyphicon-send"></i> Calcular Frete </button>
                        </div>  
                    </div><br><hr>

                    <!-- botoes de baixo e valor total -->
                    <div class="row " >
                        <div class="col-md-4 text-right"></div>
                        <div  class="col-md-3 text-right text-danger ">
                            <span>Total: R$</span><span id="total" >{{total}}</span>
                        </div>
                        <!-- botão de limpar-->
                        <div class="col-md-4 ">
                            <form name="" method="post" action="{% url 'core:remove' %}" novalidate>
                                    {% csrf_token %}
                                <input type="hidden" name="acao" value="limpar">
                                
                                <!--<input type="hidden" name="pro_id" value="">-->
                                <button class="btn btn-danger btn-block remover-tudo" > <i class="glyphicon glyphicon-trash"></i> Limpar Tudo</button>
                                <br>
                            </form>
                            <form name="pedido_confirmar" id="pedido_confirmar" method="post" action="{$PAG_CONFIRMAR}">
                                <span id="frete"></span>
                                <button class="btn btn-success btn-block" type="submit">  <i class="glyphicon glyphicon-ok"></i> Confirmar Pedido </button>
                            </form>
                        </div>
                                <!-- botão finalzar -->
                    </div>
                    <br><hr>
                </div><!-- Fim Conteudo Central-->
</div>  




{% endblock conteudo %}
{% block domready %}

let lista_de_ids = {{ lista_de_ids }} 
 $("#ajax").on("click", ".remover", function() {
    //console.log("entrou")
    let form = $(this).parent()
    let tr = $(form).parent().parent()
    let ind = $(tr).index()
    let id = lista_de_ids[ind-1]
    $(form).append("<input type='hidden' name='pro_id' value='" + id + "'>")
    let url = $(form).attr('action')
    let formData = $(form).serializeArray()
   //log(formData)
    //console.log(lista_de_ids)
    $.ajax({
        type:'POST',
        url:url,
        data:formData,
        dataType:'json',

        success: function(data){
            $(tr).fadeTo('slow', 0.3, function() {
                $(this).remove()
                lista_de_ids.splice(ind-1, 1)
                //alert(lista_de_ids)
                $("#total").text(data.total)
                //console.log(data.total)
            })
        },
        error: function(){
          // alert('Deu Erro');
          console.log('Deu Erro');
        }
         
    })
})



 $("#ajax").on("click", ".remover-tudo", function() {
    //alert("entrou")
    let form = $(this).parent()
    let tr = $(form).parent().parent()
    //let ind = $(tr).index()
    //let id = lista_de_ids[ind-1]
    //$(form).append("<input type='hidden' name='pro_id' value='" + id + "'>")
    let url = $(form).attr('action')
    let formData = $(form).serializeArray()
   //log(formData)
    //console.log(lista_de_ids)
    $.ajax({
        type:'POST',
        url:url,
        data:formData,
        dataType:'json',

        success: function(data){
            alert("success")
            $("#total").text(data.total)
           
        },
        error: function(){
          // alert('Deu Erro');
          console.log('Deu Erro');
        }
         
    })
})



  
{% endblock %}

core/templates/minhaconta.html
{% extends 'base.html' %}

{% load static %}
{% load widget_tweaks %}

{% block title %}
Minha Conta | {{block.super}}
{% endblock title %}

{% block conteudo %}
<h2> {{ teste }}</h2>
{% endblock conteudo %}