Dashboard/urls.py
from django.urls import path
from Dashboard import views

app_name='Dashboard'

urlpatterns = [
    path('', views.home, name="home"),
    path('cadastra_produto/', views.cadastra_produto, name='cadastra_produto'),
    path('exibe_produto/<int:id>/', views.exibe_produto, name='exibe_produto'),
    path('edita_produto/<int:id>/', views.edita_produto, name='edita_produto'),
    path('remove_produto/', views.remove_produto, name='remove_produto'),
    #path('pesquisa_produto/', views.pesquisa_produto, name='pesquisa_produto'),
    path('lista_produto/', views.lista_produto, name='lista_produto'),
    #path('<slug:slug_da_categoria>/', views.produto_lista, name="produto_lista_por_categoria"),
    #re_path(r'^(?P<slug>[\w_-]+)/$', views.categoria, name="categoria"),
    #path('<slug:slug_da_categoria>/<int:id>/<slug:slug_do_produto>/', views.produto_exibe, name='produto_exibe'),
]

catalogo/urls.py
from django.urls import path
from . import views

app_name='catalogo'

urlpatterns = [
    path('', views.produto_lista, name="produto_lista"),
    path('<slug:slug_da_categoria>/', views.produto_lista, name="produto_lista_por_categoria"),
    #re_path(r'^(?P<slug>[\w_-]+)/$', views.categoria, name="categoria"),
    path('<slug:slug_da_categoria>/<int:id>/<slug:slug_do_produto>/', views.produto_exibe, name='produto_exibe'),
    
]

core/urls.py
from django.urls import path
from . import views


app_name='core'

urlpatterns = [
    path('contato/', views.contato, name="contato"),
    path('minhaconta/', views.minhaconta, name="minhaconta"),
    path('carrinho/',  views.adiciona_produto_carrinho, name='carrinho'),
    path('carrinho/remove', views.remove_produto_carrinho, name='remove'),
    path('carrinho/modifica', views.modifica_produto_carrinho, name='modifica'),
    

    
]

projeto/urls.py
from django.urls import path
from django.conf.urls import include
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from catalogo.models import Categoria

urlpatterns = [
    #path('',views.index, name='index'),
    path('admin2/', admin.site.urls),
    path('admin/', include('Dashboard.urls',namespace='dashboard')),
    path('', include('core.urls',namespace='contato')),
    path('', include('core.urls',namespace='minhaconta')),
    
    #path('entrar/', LoginView.as_view(extra_context={'categorias': categorias}) ,name='login'),
    #path('sair/', LogoutView.as_view(next_page='/'),name='logout'),
    path('', include('catalogo.urls',namespace='catalogo')),
    path('autenticacao/', include('autenticacao.urls',namespace='autenticacao')),
    
]

Dashboard/models.py
from django.db import models

# Create your models here.

catalogo/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django.conf import settings
# Create your models here.
import json
class Categoria(models.Model):
    name = models.CharField('Nome',max_length=100, default=None)
    slug = models.SlugField('Identificador',max_length=100, default=None,unique=True)
    created = models.DateTimeField('Criado em', auto_now_add=True)
    modified = models.DateTimeField("Modificado em",auto_now_add=True)

    class Meta():
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'
        ordering = ['name']
        
    def get_absolute_path(self):
        return reverse('catalogo:produto_lista_por_categoria', args=[self.slug])
    def __str__(self):
        return self.name 

    def _get_unique_slug(self):
        slug = slugify(self.name)
        unique_slug = slug
        num = 1
        while Categoria.objects.filter(slug=unique_slug).exists():
            unique_slug = '{}-{}'.format(slug, num)
            num += 1
        return unique_slug
 
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self._get_unique_slug()
        super().save(*args, **kwargs)    


class Produto(models.Model):
    name = models.CharField('Nome', max_length=100,default=None)
    slug = models.SlugField('Identificador', max_length=100, default=None)
    category = models.ForeignKey('Categoria', verbose_name='Categoria',on_delete=models.CASCADE)
    description = models.TextField('Descrição', blank=True)
    price = models.DecimalField('Preço', decimal_places=2, max_digits=8, default=None)
    main_image = models.FileField('Imagem Principal', upload_to="images/", default=None)
    created = models.DateTimeField('Criado em', auto_now_add=True)
    modified = models.DateTimeField("Modificado em", auto_now_add=True)

    class Meta():
        verbose_name = 'Produto'
        verbose_name_plural = 'Produtos'
        ordering = ['name']
        
    def get_absolute_path(self):
        return reverse('catalogo:produto_exibe', args=[self.category.slug, self.id, self.slug])
        
    def __str__(self):
        return self.name 

    def _get_unique_slug(self):
        slug = slugify(self.name)
        unique_slug = slug
        num = 1
        while Produto.objects.filter(slug=unique_slug).exists():
            unique_slug = '{}-{}'.format(slug, num)
            num += 1
        return unique_slug
 
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self._get_unique_slug()
        super().save(*args, **kwargs)           
    
class Imagem(models.Model):
    slug = models.FileField('Identificador', upload_to="images/", default=None)
    product = models.ForeignKey('Produto', verbose_name='Produto',on_delete=models.CASCADE)
    

    class Meta():
        verbose_name = 'Imagem'
        verbose_name_plural = 'Imagens'
        ordering = ['product']

class Carrinho(models.Model):

    produto = models.ForeignKey('Produto', verbose_name='Produto',on_delete=models.DO_NOTHING)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             related_name='produtos',
                             on_delete=models.DO_NOTHING,
                             null=True)
    quantidade = models.IntegerField('Quantidade',default=0)
    preco = models.DecimalField('Preço', decimal_places=2, max_digits=8, default=None)
    created = models.DateTimeField('Criado em', auto_now_add=True)
    modified = models.DateTimeField("Modificado em",auto_now_add=True)


    class Meta():
        verbose_name = 'Carrinho'
        verbose_name_plural = 'Carrinho'

        ordering = ['id']
        
    def get_absolute_path(self):
        return reverse('catalogo:produto_lista_por_categoria', args=[self.slug])

            

Dashboard/forms.py
from decimal import Decimal
from django import forms
from django.core.validators import RegexValidator
from catalogo.models import Produto, Categoria
from projeto import settings
from datetime import datetime, timedelta


class PesquisaProdutoForm(forms.Form):
   class Meta:
      fields = ('busca_por')

   busca_por = forms.CharField(
      widget=forms.TextInput(attrs={'class': 'form-control form-control-sm', 'maxlength': '120'}),
      required=False)
   
   # <input type='text'
   #        name='busca_por'
   #        id='id_busca_por'
   #        class='form-control form-control-sm'
   #        maxlength='120'>

class ProdutoForm(forms.ModelForm):

    class Meta:
        model = Produto
        fields = ('id', 'category', 'name', 'price', 'description','main_image')

    id = forms.CharField(widget=forms.HiddenInput(), required=False)

    # <input type="hidden" name="produto_id" id="id_produto_id" value="xxx">


    category = forms.ModelChoiceField(
        error_messages={'required': 'Campo obrigatório.', },
        queryset=Categoria.objects.all().order_by('name'),
        empty_label='--- Selecione uma categoria ---',
        widget=forms.Select(attrs={'class': 'form-control form-control-sm'}),
        required=True)

    #      {{ form.categoria }}
    #      <select name="categoria" class="form-control form-control-sm" required id="id_categoria">
    #          <option value="" selected>--- Selecione um(a) categoria ---</option>
    #          <option value="1">Categoria 1</option>
    #          <option value="2">Categoria 2</option>
    #          <option value="3">Categoria 3</option>
    #      </select>

    name = forms.CharField(
        error_messages={'required': 'Campo obrigatório.',
                        'unique': 'Produto duplicado.'},
        widget=forms.TextInput(attrs={'class': 'form-control form-control-sm', 'maxlength': '120'}),
        required=True)

    # <input type="text"
    #        name="nome"
    #        id="id_nome"
    #        class="form-control form-control-sm"
    #        maxlength="120"
    #        required>

    price = forms.CharField(
        localize=True,
        error_messages={'required': 'Campo obrigatório.', },
        validators=[RegexValidator(regex='^[0-9]{1,7}(,[0-9]{2})?$', message="Informe o valor no formato 9999999,99.")],
        widget=forms.TextInput(attrs={'class': 'form-control form-control-sm',
                                      'maxlength': '10',
                                      'onkeypress': 'return (event.charCode >= 48 && event.charCode <= 57) || event.charCode == 44'}),
        required=True)

    # <input type="text"
    #        name="preco"
    #        id="id_preco"
    #        class="form-control form-control-sm"
    #        maxlength="10"
    #        onkeypress="return (event.charCode >= 48 &amp;&amp; event.charCode <= 57) || event.charCode == 44"
    #        required="">

    description = forms.CharField(
       widget=forms.TextInput(attrs={'class': 'form-control form-control-sm'}),
       required=False)
    
    # <input type='text'
    #        name='data_cadastro'
    #        class='form-control form-control-sm'
    #        required=''
    #        id='id_data_cadastro'
    #        maxlength='10'>


    main_image = forms.ImageField  (
        error_messages={'required': 'Campo obrigatório.', },
        widget=forms.ClearableFileInput(),
        required=False
    )
    

    def clean_price(self):
        price = self.cleaned_data.get('price')
        
        if not price:
            return price
        
        price = Decimal(price.replace(',', '.'))

        return price
        
    
        

class RemoveProdutoForm(forms.Form):
    class Meta:
        model = Produto
        fields = ('id')

    id = forms.CharField(widget=forms.HiddenInput(), required=True)

    # <input type="hidden" name="produto_id" id="id_produto_id" value="xxx">

Dashboard/views.py
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.core.paginator import Paginator

from Dashboard.forms import ProdutoForm, RemoveProdutoForm, PesquisaProdutoForm
from catalogo.models import Produto, Categoria
from datetime import datetime, timedelta
from django.contrib.auth.decorators import login_required
from django.core.files.storage import FileSystemStorage


@login_required
def home(request):
    
    if request.user.is_superuser:   
        return render (request, 'Dashboard/home.html')
    else:

        return redirect ('/')  


  

@login_required
def cadastra_produto(request):
    
    if request.POST:
        
        produto_id = request.POST.get('id')
        print(request.POST.get('main_image'))
        if produto_id:
            
            produto = get_object_or_404(Produto, pk=produto_id)
            produto_form = ProdutoForm(request.POST, instance=produto)
            
            
        else:
            
            
            produto_form = ProdutoForm(request.POST)
            

        if produto_form.is_valid():
            
            produto = produto_form.save(commit=False)
            if produto_id:
                messages.add_message(request, messages.INFO, 'Produto alterado com sucesso!')
            else:
                produto.user = request.user
                messages.add_message(request, messages.INFO, 'Produto cadastrado com sucesso!')
            produto.save()
            return redirect('Dashboard:lista_produto')
        else:
            messages.add_message(request, messages.ERROR, 'Corrija o(s) erro(s) abaixo.')
    else:
        produto_form = ProdutoForm()

    

    return render(request, 'Dashboard/cadastra_produto.html', {
       'form': produto_form,
       
    })


def exibe_produto(request, id):
    produto = get_object_or_404(Produto, pk=id)
    form_remove_produto = RemoveProdutoForm(initial={'id': id})
    return render(request, 'Dashboard/exibe_produto.html', {
       'produto': produto,
       'form_remove_produto': form_remove_produto
    })

def edita_produto(request, id):
    produto = get_object_or_404(Produto, pk=id)
    produto_form = ProdutoForm(instance=produto)
    produto_form.fields['id'].initial = id

    
    return render(request, 'Dashboard/cadastra_produto.html', {
       'form': produto_form,
       
    })

def lista_produto(request):
    form = PesquisaProdutoForm(request.GET)
    
    if request.POST:  
        produto_id = request.POST.get('id')
        produto = get_object_or_404(Produto, id=produto_id)
        
        produto.delete()
        messages.add_message(request, messages.INFO, 'Produto removido com sucesso.')
        
    if form:
        if form.is_valid():
            busca_por = form.cleaned_data['busca_por']
            lista_de_produtos = Produto.objects.filter(name__icontains=busca_por).order_by('name')
    else:    
        lista_de_produtos = Produto.objects.all()

    paginator = Paginator(lista_de_produtos, 5)
    pagina = request.GET.get('page')
    produtos = paginator.get_page(pagina)
    
    return render(request, 'Dashboard/lista_produto.html', {
        'produtos': produtos,
        'form': form,
        'busca': busca_por
        
    })

def remove_produto(request):
#   form_remove_produto = RemoveProdutoForm(request.POST)
#   if form_remove_produto.is_valid:
      # produto_id = form_remove_produto.cleaned_data['produto_id']
    if request.POST:  
        produto_id = request.POST.get('id')
        produto = get_object_or_404(Produto, id=produto_id)
        
        produto.delete()
        messages.add_message(request, messages.INFO, 'Produto removido com sucesso.')
        produtos = Produto.objects.all()

    return render(request, 'Dashboard/lista_produto.html', {
        'produtos': produtos,
        
    })
#   else:
#      raise ValueError('Ocorreu um erro inesperado ao tentar remover um produto.')


      

Dashboard/templates/Dashboard/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'assets/admin/plugins/images/favicon.png' %}">
    <title>{% block title %}
           Admin
      {% endblock title %}</title>
    <!-- Bootstrap Core CSS -->
    <link href="{% static 'assets/admin/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Menu CSS -->
    <link href="{% static 'assets/admin/plugins/bower_components/sidebar-nav/dist/sidebar-nav.min.css' %}" rel="stylesheet">
    <!-- animation CSS -->
    <link href=" {% static 'assets/admin/css/animate.css' %}" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="{% static 'assets/admin/css/style.css' %}" rel="stylesheet">
    <!-- color CSS -->
    <link href="{% static 'assets/admin/css/colors/default.css' %}" id="theme" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->
</head>

<body class="fix-header">
    <!-- ============================================================== -->
    <!-- Preloader -->
    <!-- ============================================================== -->
    <div class="preloader">
        <svg class="circular" viewBox="25 25 50 50">
            <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="2" stroke-miterlimit="10" />
        </svg>
    </div>
    <!-- ============================================================== -->
    <!-- Wrapper -->
    <!-- ============================================================== -->
    <div id="wrapper">
        <!-- ============================================================== -->
        <!-- Topbar header - style you can find in pages.scss -->
        <!-- ============================================================== -->
        <nav class="navbar navbar-default navbar-static-top m-b-0">
            <div class="navbar-header">
                <div class="top-left-part">
                    <!-- Logo -->
                    <a class="logo" href="dashboard.html">
                        <!-- Logo icon image, you can use font-icon also --><b>
                            <!--This is dark logo icon--><img src="{% static 'assets/admin/plugins/images/admin-logo.png' %}" alt="home"
                                class="dark-logo" />
                            <!--This is light logo icon--><img src="{% static 'assets/admin/plugins/images/admin-logo-dark.png' %}" alt="home"
                                class="light-logo" />
                        </b>
                        <!-- Logo text image you can use text also --><span class="hidden-xs">
                            <!--This is dark logo text--><img src="{% static 'assets/admin/plugins/images/admin-text.png' %}" alt="home"
                                class="dark-logo" />
                            <!--This is light logo text--><img src="{% static 'assets/admin/plugins/images/admin-text-dark.png' %}" alt="home"
                                class="light-logo" />
                        </span> </a>
                </div>
                <!-- /Logo -->
                <ul class="nav navbar-top-links navbar-right pull-right">
                    <li>
                        <a class="nav-toggler open-close waves-effect waves-light hidden-md hidden-lg"
                            href="javascript:void(0)"><i class="fa fa-bars"></i></a>
                    </li>
                    
                   
                </ul>
            </div>
            <!-- /.navbar-header -->
            <!-- /.navbar-top-links -->
            <!-- /.navbar-static-side -->
        </nav>
        <!-- End Top Navigation -->
        <!-- ============================================================== -->
        <!-- Left Sidebar - style you can find in sidebar.scss  -->
        <!-- ============================================================== -->
        <div class="navbar-default sidebar" role="navigation">
            <div class="sidebar-nav slimscrollsidebar">
                <div class="sidebar-head">
                    <h3><span class="fa-fw open-close"><i class="ti-close ti-menu"></i></span> <span
                            class="hide-menu">ADMIN</span></h3>
                </div>
                <ul class="nav" id="side-menu">
                    <li style="padding: 70px 0 0;">
                        <a href="{% url 'Dashboard:home' %}" class="waves-effect"><i class="fa fa-clock-o fa-fw"
                                aria-hidden="true"></i>Home</a>
                    </li>
                    <li>
                        <a href="profile.html" class="waves-effect"><i class="fa fa-user fa-fw"
                                aria-hidden="true"></i>Profile</a>
                    </li>
                    <li>
                        <a href="basic-table.html" class="waves-effect"><i class="fa fa-table fa-fw"
                                aria-hidden="true"></i>Categorias</a>
                    </li>
                    <li>
                        <a href="{% url 'Dashboard:lista_produto' %}" class="waves-effect"><i class="fa fa-product-hunt fa-fw"
                                aria-hidden="true"></i>Produtos</a>
                    </li>
                    <li>
                        <a href="map-google.html" class="waves-effect"><i class="fa fa-picture-o fa-fw"
                                aria-hidden="true"></i>Imagens</a>
                    </li>
                   
                </ul>
                <hr>
                <ul class="nav" id="side-menu">
                    <li>
                        <a href="dashboard.html" class="waves-effect"><i class="fa fa-cogs fa-fw"
                                aria-hidden="true"></i>Configurações</a>
                    </li>
                    <li>
                        <a href="{% url 'catalogo:produto_lista' %}" class="waves-effect"><i class="fa fa-user fa-fw"
                                aria-hidden="true"></i>Sair</a>
                    </li>
                    
                </ul>
                
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- End Left Sidebar -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Page Content -->
        <!-- ============================================================== -->
        <div id="page-wrapper">
            <div class="container-fluid">
               
                <div class="row">
                    <div class="col-md-12">
                         {% block conteudo %}
                     {% endblock conteudo %}
                    </div>
                </div>
            </div>
            <!-- /.container-fluid -->
            <footer class="footer text-center"> 2017 &copy; Ample Admin brought to you by wrappixel.com </footer>
        </div>
        <!-- ============================================================== -->
        <!-- End Page Content -->
        <!-- ============================================================== -->
    </div>
    {% block modal %}
    {% endblock  %}
    {% block scripts %}    
    {% endblock %}
    <!-- /#wrapper -->
    <!-- jQuery -->
    <script src="{% static 'assets/admin/plugins/bower_components/jquery/dist/jquery.min.js' %}"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'assets/admin/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <!-- Menu Plugin JavaScript -->
    <script src="{% static 'assets/admin/plugins/bower_components/sidebar-nav/dist/sidebar-nav.min.js' %}"></script>
    <!--slimscroll JavaScript -->
    <script src="{% static 'assets/admin/js/jquery.slimscroll.js' %}"></script>
    <!--Wave Effects -->
    <script src="{% static 'assets/admin/js/waves.js' %}"></script>
    <!-- Custom Theme JavaScript -->
    <script src="{% static 'assets/admin/js/custom.min.js' %}"></script>
</body>

</html>

Dashboard/templates/Dashboard/home.html
{% extends "Dashboard/base.html" %}

{% load static %}

{% block titulo %}
HOME
{% endblock %}

{% block conteudo %}



<div>
   <h3 class="box-title" align="center">HOME</h3>
</div>
<div class="white-box">

   
   <div class="container">
        <img align="center"  src="{% static 'assets/imagens/e0f7b30d35e7cb462626125bab395ab0.jpg'%}">
   
   </div>
  
   
  
  
   

</div>



{% endblock %}

Dashboard/templates/Dashboard/index.html
{% extends "Dashboard/base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block title %}
Home | {{block.super}}
{% endblock title %}

{% block conteudo %}

{% endblock conteudo %}

Dashboard/templates/Dashboard/lista_produto.html
{% extends "Dashboard/base.html" %}

{% load static %}

{% block titulo %}
Cadastro de Produtos
{% endblock %}

{% block conteudo %}



<div>
   <h3 class="box-title" align="center">Listagem de Produtos</h3>
</div>
<div class="white-box">

   
   <div class="row">
      <div class="col-md-4">
         <a class="btn btn-success" href="{% url 'Dashboard:cadastra_produto' %}" align="right">Cadastrar</a>
      </div>
      <div class="col-md-2">
        
      </div>
      <div class="col-md-6">
         <form action="{% url 'Dashboard:lista_produto' %}" method='GET'>
            <div class='form-group row' style='margin-bottom: 10px;'>
               <label for='id_busca_por' class='col-md-2 col-form-label font-weight-bold'>
                  Nome
               </label>
               <div class='col-md-5'>
                  {{ form.busca_por }}
               </div>
               <div class="col-md-5 ">
                  <button type='submit' class='btn btn-primary'>
                     <i class="fa fa-search"></i> 
                     Pesquisar
                  </button>
               </div>


            </div>


            
               
            
         </form>
      </div>

   </div>
   <br>
   {% if messages %}
   <div class="row mb-3">
      <div class="col-12">
         {% for message in messages %}
         <ul class="list-group rounded {{ message.tags }}">
            {# Supondo a utilização de apenas info e danger #}
            <li style="padding-top: 7px; padding-bottom: 7px;"
               class="list-group-item list-group-item-{% if message.tags == 'info' %}info{% else %}danger{% endif %}">
               {{ message }}
            </li>
         </ul>
         {% endfor %}
      </div>
   </div>
   {% endif %}
   <div class="table-responsive">
      <table class="table table-bordered">
         <thead class="thead-dark">
            <tr>
               <th>Categoria</th>
               <th>Nome</th>
               <th>Preço</th>
               <th>Descrição</th>
               <th>Ação</th>
            </tr>
         </thead>
         <tbody>
            {% for produto in produtos  %}
            <tr>
               <td width="15%">{{ produto.category.name }}</td>
               <td width="15%">{{ produto.name }}</td>
               <td width="10%">{{ produto.price }}</td>
               <td width="25%">{{ produto.description }}</td>
               <td class="row">
                  <div class="col-md-3">
                     <a id="botao_editar" href="{% url 'Dashboard:edita_produto' produto.id %}" class="btn btn-primary">
                        Editar
                     </a>
                  </div>
                  <div style="background-color:red"></div>
                  <div class="col-md-3">
                     <!--<form id="form_remove_produto" style="margin-bottom: 0px;"
                        action="{% url 'Dashboard:lista_produto' %}" method="post" novalidate>
                        {% csrf_token %}
                        <input type="hidden" name="id" value="{{ produto.id }}"> -->
                     <button id="botao_remover" class="btn btn-danger" data-toggle="modal" data-target="#exampleModal">
                        Excluir
                     </button>
                     <!--</form>-->


                  </div>
                  <div class="col-md-6"></div>
               </td>

            </tr>
            {% block modal %}
            <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
               aria-hidden="true">
               <div class="modal-dialog" role="document">
                  <div class="modal-content">
                     <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Excluir</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                           <span aria-hidden="true">&times;</span>
                        </button>
                     </div>
                     <div class="modal-body">
                        Deseja Realmente excluir esse Produto?
                     </div>
                     <div class="modal-footer">
                        <div class="row">
                           <div class="col-md-6">
                              <button type="button" class="btn btn-secondary btn-block"
                                 data-dismiss="modal">Close</button>
                           </div>
                           <div class="col-md-6">
                              <form id="form_remove_produto" action="{% url 'Dashboard:lista_produto' %}" method="post"
                                 novalidate>
                                 {% csrf_token %}
                                 <input type="hidden" name="id" value="{{ produto.id }}">
                                 <button id="botao_remover" class="btn btn-danger btn-block" data-toggle="modal"
                                    data-target="#exampleModal">
                                    Excluir
                                 </button>
                              </form>
                           </div>
                        </div>

                     </div>
                  </div>
               </div>
            </div>

            {% endblock %}

            {% endfor %}
         </tbody>
      </table>
   </div>
   {% if produtos %}
   <nav aria-label="Navegação de página" class="pt-3">
      <ul class="pagination justify-content-center">
         {% if produtos.has_previous %}
         <li class="page-item"><a class="page-link" href="?page={{ produtos.previous_page_number }}">Anterior</a></li>
         {% endif %}


         {% for x in produtos.paginator.page_range %}
         <li class="page-item {% if x == produtos.number %}active{% endif %}"><a class="page-link"
               href="?page={{x}}">{{x}}</a></li>
         {% endfor %}



         {% if produtos.has_next %}
         <li class="page-item"><a class="page-link" href="?page={{ produtos.next_page_number }}">Próximo</a></li>
         {% endif %}
      </ul>
   </nav>
   {% endif %}

</div>
</div>


{% endblock %}





{% block scripts %}
<script>
   $('#myModal').on('shown.bs.modal', function () {
      $('#myInput').trigger('focus')
   })


</script>
{% endblock  %}